name: Workflow To Test Action

on: [push]

jobs:
  diff:
    runs-on: ubuntu-latest
    name: Test Action 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Simple test to download a file
        uses: actions/github-script@v4
        with:
          file-url: 'https://lock.demo.domoscio.com/assets/libs/dom-toolkit-6a01f0804872a16bdb08215da531584b1e322cfca4c7cdd237a5fabb1f1a503d.css'
          file-name: 'toolkit-github-actions.css'
          location: './css'
      - run: echo "The file was downloaded to ${{ steps.download-poetry-simple.outputs.file-path }}"
      