name: Download a file
on: push
jobs:
    diff:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/github-script@v4
            with:
                file-url: 'https://lock.demo.domoscio.com/assets/libs/dom-toolkit-6a01f0804872a16bdb08215da531584b1e322cfca4c7cdd237a5fabb1f1a503d.css'
                file-name: 'toolkit-github-actions.css'
                location: './css'
                